kind: pipeline
name: default

steps:
- name: test
  image: shmolyneaux/ziglang:0.12.1
  commands:
    - zig build
    - apk add python3
    - cat test_list | xargs ./run_tests

trigger:
  event:
  - push
