kind: pipeline
name: default

steps:
- name: test
  image: shmolyneaux/ziglang:0.9.0-dev.1139
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
    - zig build
    - apk add python3
    - ./run_tests tests/check_output/print_int*.shm tests/check_output/print_str*.shm tests/check_output/print_multiple_args.shm tests/check_output/print_with_comments.shm

trigger:
  event:
  - push
