kind: pipeline
name: default

steps:
- name: test
  image: shmolyneaux/ziglang:0.9.0-dev.1139
  environment:
    SSH_KEY:
      from_secret: SSH_KEY
  commands:
    - zig build
    - apk add python3
    - cat test_list | xargs ./run_tests

trigger:
  event:
  - push
