kind: pipeline
name: default

steps:
- name: test
  image: shmolyneaux/shimlang-builder:latest
  commands:
    - cp -r * /src/shimlang
    - cd /src/shimlang
    - . $HOME/.cargo/env
    - cargo +nightly build --release -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-musl
    - objcopy --only-keep-debug target/x86_64-unknown-linux-musl/release/min-static symbols.dbg
    - cp target/x86_64-unknown-linux-musl/release/min-static stripped
    - strip stripped
    - bloaty stripped -d symbols -n 100 -s file --debug-file symbols.dbg

trigger:
  event:
  - push
