[workspace]

members = [
    "shimlang",
    "libshim",
    "acollections",
    "tally-ho",
]

exclude = [
    # We keep this apart since it relies on wasm-only intrinsics for memory
    "shimlang-wasm"
]

[profile.release]
debug = true
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
